# Generated by Django 3.0.1 on 2019-12-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontoturistico_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='cometarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
